new readme
FlagOpen/FlagPerf pull request #335
Opened 2023-11-22 08:27 UTC by shh2000

2023-11-22 08:53 UTC, SiyuHu95 requested changes

2023-11-22 08:53 UTC, SiyuHu95 commented on README.md
> +### 如何参与共建FlagPerf
```
### 参与共建FlagPerf

> 开发者教程：更多操作教程见 [docs-zh](./docs-zh) 

为了更直观的展示厂商参与共建的实际工作量，下面给出6个已经合并进FlagPerf，面向不同特征厂商的Pull Request。

1. 模型训练适配适配

    - **第一次参与训练**适配工作的内容较多。除了适配模型case外，还需要适配厂商的dockerfile、monitor等，如[#246](https://github.com/FlagOpen/FlagPerf/pull/246)
    - **后续参与训练**适配工作量较小：
        - 如厂商以**cuda兼容**路线设计软硬件，典型适配case [#170](https://github.com/FlagOpen/FlagPerf/pull/170)
        - 如厂商**不兼容cuda**，则需要额外修改后端通信方案等等，典型适配case [#288](https://github.com/FlagOpen/FlagPerf/pull/288)。当case较复杂时，可能需要重写部分计算方式、半精度接口等，如[#158](https://github.com/FlagOpen/FlagPerf/pull/158)。

2. 模型推理适配

  - **第一次参与推理**适配的工作内容较多。除了适配case外，还包括厂商的dockerfile、编译器实现方式、monitor等，如 [#256](https://github.com/FlagOpen/FlagPerf/pull/256)
  - **后续参与推理**适配时，通常不需要适配工作量、仅需运行软件完成测试。如 [#227](https://github.com/FlagOpen/FlagPerf/pull/227)

## FlagPerf 合作伙伴


![cooperation](assets/imgs/logo1122.png)

```

2023-11-22 08:53 UTC, SiyuHu95 commented on README.md
> +![cooperation](assets/imgs/logo1122.png)
直接放logo就行了。

2023-11-22 08:53 UTC, SiyuHu95 commented on README.md
> +flagperf@baai.ac.cn
如有疑问，可以发送邮件至 flagperf@baai.ac.cn，或在 [issue](https://github.com/FlagOpen/FlagPerf/issues) 中说明情况。

2023-11-22 08:53 UTC, SiyuHu95 commented on README.md
> +### FlagPerf是什么
## FlagPerf 简介

--
从二级标题开始写。

2023-11-22 08:53 UTC, SiyuHu95 commented on README.md
> +### 📣 **评测方案及特性**
```
## FlagPerf 评测亮点
```

2023-11-23 05:50 UTC, upvenly approved these changes

2023-11-23 06:02 UTC, yuzhou03 approved these changes

2023-11-24 03:07 UTC, merged